# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e964bee7abd22745a54d365121745afe6406e4772eb5a6f11b2ffeb1cc4afeb04e686d5ae5913e295954cfa4ef0914b0b212d87c54aa5026cd6a5bf98971755

test:
  secret_key_base: f80e82c8ff42baf6aeeced20c0d41cc2aedb2dce7ec67ba3f480bf6ee9771993c97fb514ce731bf8f3b740d82d5199d10c9e740315b28e58514a5fcb2e695724

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
